# Generated by Django 2.1.3 on 2018-12-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeIdol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JapaneseName', models.CharField(max_length=30)),
                ('KanjiName', models.CharField(max_length=30)),
                ('KoreanName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birth', models.DateField()),
                ('bloodType', models.CharField(max_length=5)),
                ('BWH', models.CharField(max_length=20)),
                ('hobby', models.TextField()),
                ('bornPlace', models.TextField()),
                ('Color', models.CharField(max_length=10)),
                ('Voice', models.CharField(max_length=30)),
                ('mainPicture', models.ImageField(upload_to='')),
                ('signPicture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JapaneseName', models.CharField(max_length=30)),
                ('KanjiName', models.CharField(max_length=30)),
                ('KoreanName', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('birth', models.DateField()),
                ('bloodType', models.CharField(blank=True, max_length=5, null=True)),
                ('BWH', models.CharField(blank=True, max_length=20, null=True)),
                ('hobby', models.TextField(blank=True, null=True)),
                ('bornPlace', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=10)),
                ('voice', models.CharField(max_length=30)),
                ('mainPicture', models.ImageField(upload_to='')),
                ('signPicture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='idol',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idolmaster.Production'),
        ),
        migrations.AddField(
            model_name='beforeidol',
            name='nowIdol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idolmaster.Idol'),
        ),
        migrations.AddField(
            model_name='beforeidol',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idolmaster.Production'),
        ),
    ]
