# Generated by Django 2.1.1 on 2018-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idolmaster', '0002_auto_20180920_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='bornPlace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
