# Generated by Django 2.1.1 on 2018-09-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idolmaster', '0003_auto_20180920_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='idol',
            old_name='Voice',
            new_name='voice',
        ),
    ]
