# Generated by Django 2.1.1 on 2018-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idolmaster', '0004_auto_20180920_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='BWH',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='idol',
            name='bloodType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='idol',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idol',
            name='hobby',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idol',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
